# Generated by Django 4.2 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='miniphoto1',
            field=models.ImageField(blank=True, upload_to='main/static/main/mini_images', verbose_name='1 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='miniphoto2',
            field=models.ImageField(blank=True, upload_to='main/static/main/mini_images', verbose_name='2 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='deskription',
            field=models.TextField(blank=True, verbose_name='описание товара ( для отдельной страницы )'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='main/static/main/prod_images', verbose_name='фотография товара ( для каталога )'),
        ),
    ]
