# Generated by Django 4.2 on 2023-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_options_alter_catalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='sizes',
            field=models.CharField(default=0, max_length=50, verbose_name='размеры'),
            preserve_default=False,
        ),
    ]
