# Generated by Django 4.2 on 2023-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_catalog_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='brand',
            field=models.CharField(default=0, max_length=50, verbose_name='Бренд товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='sizes',
            field=models.TextField(max_length=150, verbose_name='размеры'),
        ),
    ]
