# Generated by Django 3.2.20 on 2023-07-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230708_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments2',
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
