# Generated by Django 3.2.20 on 2023-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230709_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='miniphoto3',
            field=models.ImageField(blank=True, upload_to='media/prod_images', verbose_name='3 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='miniphoto4',
            field=models.ImageField(blank=True, upload_to='media/prod_images', verbose_name='4 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='miniphoto1',
            field=models.ImageField(blank=True, upload_to='media/prod_images', verbose_name='1 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='miniphoto2',
            field=models.ImageField(blank=True, upload_to='media/prod_images', verbose_name='2 фотография товара ( для отдельной страницы )'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(upload_to='media/prod_images', verbose_name='фотография товара ( для каталога )'),
        ),
    ]
