# Generated by Django 3.2.20 on 2023-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230710_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
