# Generated by Django 3.2.20 on 2023-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230715_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('news_text', models.TextField(verbose_name='текст новости')),
                ('photo', models.ImageField(upload_to='media/prod_images', verbose_name='картинка для новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
