# Generated by Django 3.2.20 on 2023-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/prod_images', verbose_name='картинка для новости'),
        ),
    ]
